### ISSUE TITLE
Shortcode playlist doesn't working

### ISSUE THREAD

**Issue by kolyaraketa** [birgire/wpse-playlist#10]
Hi! I trying to use wp_playlist_shortcode for creating playlist with audio-files from all blog posts, i have array with ID.

I trying this code, and its doesn't working:
$attch_id = array('76', '73', '70', '67');
wp_playlist_shortcode( array( 'ids' => '$attch_id' );

where is the mistake? How i can use wp_playlist_shortcode? 
Thanks )

**Comment by birgire** [comment]
Hi @kolyaraketa 

Are you trying to use the plugin?

I'm not sure how your question relates to the plugin usage?

The plugin is using shortcodes to handle external playlist sources.

Otherwise your code has few issues, the ids should be a comma seperated string,

    'ids' => '12,23,34,45',

**Comment by kolyaraketa** [comment]
Hi! Thank you for your answer! 
Now your plugin is not built into wordpress?
Audio shortcodes working fine.
