### ISSUE TITLE
Play progress bar is below the play bar

### ISSUE THREAD

**Issue by gitdexby** [birgire/wpse-playlist#12]
Hi, really like the plugin - but I'm having some problems. The play progress bar is not inside of the play bar, And the volume control is missing. See this here:

http://prnt.sc/clyfud
http://prnt.sc/clykxq

Any ideas on this? I copied your own playlist short code example:

`[_playlist type="audio" current="yes" tracklist="yes" tracknumbers="yes" images="no" artist="no"]
    [_track title="Davenport Blues" src="http://s.w.org/images/core/3.9/DavenportBlues.mp3"]
    [_track title="Dixie Blues" src="http://s.w.org/images/core/3.9/Louisiana_Five-Dixie_Blues-1919.mp3"]
[/_playlist]`

**Comment by birgire** [comment]
Hi @gitdexby 

Good to hear you find it useful.

I guess it's something related to your theme, as the progress bar shows correctly in the Twenty Sixteen default theme.

Did you test the default themes?

**Comment by birgire** [comment]
I'm closing this thread due to inactivity.
