### ISSUE TITLE
Multiple type src video

### ISSUE THREAD

**Issue by durandarno** [birgire/wpse-playlist#14]
It's possible to make 2 sources of video for 1 track?
Like this  : 
[_track caption="PB DUDU 1 : Échec et maths" src="https://mathix.org/video/problemes_ouverts/PB_DUDU/PBDUDU1.mp4.mp4" webm="https://mathix.org/video/problemes_ouverts/PB_DUDU/PBDUDU1.mp4.webm" meta_length_formatted="1:03"]

**Comment by birgire** [comment]
Hi @durandarno 

The native playlist only supports the src attribute, as we see here:

https://github.com/WordPress/WordPress/blob/fe0b8a2aaf49ff5f33a866309ed8730fd7675674/wp-includes/js/mediaelement/wp-playlist.js

so the same applies for the plugin.

If you can see a way there, then I'm always open for suggestions ;-)
