### ISSUE TITLE
Ampersand in title or meta_artist

### ISSUE THREAD

**Issue by killexx** [birgire/wpse-playlist#15]
Has anyone encountered a problem with a result of 'title' or 'meta_artist' parameters that have ampersand?

In my case Title represents ampersand as &#_038;
and Artist as &_amp;

Is there some way to make it normal for reading in media player?
![2017 05 12-17 14 02](https://cloud.githubusercontent.com/assets/12859497/26001937/a97d5bd6-3736-11e7-93f6-7cf148599886.png)

**Comment by birgire** [comment]
Hi @killexx 

I guess the visual editor has changed `&` to `&amp;.`

You can e.g. try to view it in the Text mode instead and change from &amp; to & and save.

Hopefully that works.

**Comment by killexx** [comment]
The problem is that normal/direct output to html is normal, but when string goes through json list of tracks ampersand becomes encoded, and doesn't decode back to normal.

![2017 05 12-18 11 04](https://cloud.githubusercontent.com/assets/12859497/26004404/68965dd6-373e-11e7-8e44-968893519c89.png)

**Comment by birgire** [comment]
Thanks for the screenshot, how does it look like in the Text mode in the editor?

**Comment by killexx** [comment]
Normal shortcode usage don't have such a problem. So I will close this issue.

I try to use this plugin for direct php output without a shortcode, and in ajax request, but it seems that it is impossible or buggy, because many problems occur:
1) shortcodes don't work in ajax requests;
2) some symbols have problems with encoding
