### ISSUE TITLE
thanks and question - how to get at more native WordPress playlist attributes

### ISSUE THREAD

**Issue by jonlever** [birgire/wpse-playlist#16]
thanks for this plugin, has been very useful to me.

Currently I'd like to completely eliminate the playlist title section. Thought I could maybe adapt the plugin php? Don't really want to have something that applies site-wide in css as there are other pages with players that benefit from the playlist. Any guidance/advice welcome.

**Comment by jonlever** [comment]
forget that, I can suppress the single item tracklist and it makes more sense. Would like to reduce the size of the area above the play bar though as the is just the title line then equivalent of about four blank lines of space. Can't find a way to reduce it currently.

**Comment by jonlever** [comment]
found a way :)

.wp-playlist-current-item {
    height: 20px !important;
}
can probably live with this

**Comment by birgire** [comment]
@jonlever glad to hear you find it useful.

Thanks for sharing your workaround.

Guess one could restrict it further by the default `.wpse-playlist` playlist class or via some other custom class attribute.

Here are some older answers I've posted, don't know if they help here?

https://wordpress.stackexchange.com/a/143281/26350

https://wordpress.stackexchange.com/a/228110/26350

https://wordpress.stackexchange.com/a/142974/26350
