### ISSUE TITLE
Can not play in Chromium browser.

### ISSUE THREAD

**Issue by syshut** [birgire/wpse-playlist#17]
Hi,

Thanks for the plugin, and I'm using is on my site for a while.

Today I test it in my Chromium 64.0 browser this address:
https://xlino.com/projects/wordpress-playlist-shortcode-with-external-audio-or-video-files/
but the music cannot play normally as my other browsers can, such as Fx 56.0 and IE 11, etc. The buttons are not even shown.

I'm not professionnal at programming so I don't know what's wrong and how to solve it. Could you please tell me what to do?

https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/518848/mini_installer.exe
The address above is the browser I ran the test.

![pic](https://user-images.githubusercontent.com/21360506/33163023-5710d97a-d067-11e7-8084-71b4d97a124b.jpg)

**Comment by birgire** [comment]
Hi @syshut and thanks for your report.

I'm just wondering if the native playlist works for you in Chromium?

**Comment by syshut** [comment]
@birgire 
How to enable native playlist and test it?

**Comment by birgire** [comment]
@syshut I updated the demo page with a native example for comparison.

**Comment by syshut** [comment]
@birgire 
Also can not play. So does it mean there is something wrong with the chromium browser? Or with the native playlist.
![nn](https://user-images.githubusercontent.com/21360506/33470272-56450b60-d6a2-11e7-89c2-6e88c9756746.jpg)

**Comment by birgire** [comment]
Thanks for checking the native playlist.

Not sure if this is WordPress bug or Chromimum bug? 

Any error messages?

**Comment by syshut** [comment]
@birgire 
Not any error message, what I see on the web page is just like the snapshot above.
OK, if it is not the plugin's bug I'd like to close this issue.
Thank you for the plugin again!
