### ISSUE TITLE
Feature Request: Automatic Updates

### ISSUE THREAD

**Issue by BlaineMoore** [birgire/wpse-playlist#2]
Thanks for the speedy fix to the WordPress 4.0 issue.

Do you have any plans to put this plugin into the WordPress plugin repository? And if not, would I be out of place to request automatic updates be implemented?

I've seen some tutorials on how to implement automatic updates directly from GitHub, and have actually seen a few projects for making it easy.

For example: 
* [tuts+ Tutoral](http://code.tutsplus.com/tutorials/distributing-your-plugins-in-github-with-automatic-updates--wp-34817)
* [afragen's Github Update plugin](https://github.com/afragen/github-updater)
* [jkudish's Github update class](https://github.com/jkudish/WordPress-GitHub-Plugin-Updater)

Thanks for considering.

**Comment by dbranes** [comment]
I added a support for the GitHub Updater

See:
https://github.com/birgire/wpse-playlist/commit/fb07f957c209709835cbc874a6a4adeed890bacc

**Comment by birgire** [comment]
I added a support for the GitHub Updater

See:
https://github.com/birgire/wpse-playlist/commit/fb07f957c209709835cbc874a6a4adeed890bacc
