### ISSUE TITLE
Google Drive links

### ISSUE THREAD

**Issue by mikigp** [birgire/wpse-playlist#20]
Hi!
I use this plugin since 2015 on my wordpress site, with external links to my Dropbox mp3 files, and it works like a charm!

In these days I tried to move my files to Google Drive, convert the "Shared link" to a "Direct Download link" (like described in several webpages) and then to post my playlists in the same way, but in this case the plugin doesn't start playing.

Any idea to make it work with Google Drive links?

**Comment by birgire** [comment]
Hi @mikigp 

Glad to hear it has worked for you

I've not tried it with Google Drive, but you could try to add it as a single audio  (i.e. not using the plugin) into WordPress post to see if that works (e.g. via audio block). Also try to have it with  a file-type-ending (.mp3) in the plugin to see if that helps.

**Comment by mikigp** [comment]
Hi @birgire 
I tried to add my Google Drive shared link with the audio html tag and it works.
The problem is that i need to create a playlist with many .mp3 or .m4a audio files, possibly with track names.
Nothing changed when I added the extension to the link.
I also tried to add file-type definition into the track shortcode... but without success.

**Comment by birgire** [comment]
I wonder if you can share a temporary .mp3 GD link ?

**Comment by birgire** [comment]
Thanks, 

As the plugin uses the playlist engine from core, I think that might be the issue,that it is not supporting GET parameters well.

Do you know if it's possible to get the .m4a file extension to the GD link?

I tested 

https://googledrive.com/host/1lPriIg-Frd-OpEWnmbxvivrxNp6HOfh9/Riscaldamento01.m4a

suggested by:

https://webapps.stackexchange.com/questions/65763/how-can-i-hotlink-an-mp3-in-google-drive-with-a-url-ending-in-mp3

but it seems deprecated access and gives 404.

**Comment by birgire** [comment]
This seems to work, i.e. if you make sure the first GET parameter is the id:

`[_track title="Test" caption="Testing" meta_artist="Test"  src="https://drive.google.com/uc?id=1lPriIg-Frd-OpEWnmbxvivrxNp6HOfh9"]`

**Comment by mikigp** [comment]
It works!!! Tested on others .m4a and .mp3 files!
Thank you very much @birgire !

**Comment by birgire** [comment]
Great glad to hear it worked for you @mikigp

**Comment by honoluluman2** [comment]
@birgire Thank you for this great plugin! Is it possible to make it work also for large google drive audio files (more than 25MB) ? 
I have tried this tutorial https://bytesbin.com/google-drive-direct-download-link-large-files/ but i am not sure if i can get a url along with the API query ?alt=media&key=APIKey working.

**Comment by birgire** [comment]
Hi @honoluluman2 
is it ok to use 

https://www.googleapis.com/drive/v3/files/FileID?key=APIKey

instead of

https://www.googleapis.com/drive/v3/files/FileID?alt=media&key=APIKey

i.e. skip 

alt=media&

**Comment by honoluluman2** [comment]
@birgire thank you for your fast reply and happy new year!
It seems that it doesn't work.
I have tried all possible combinations 

https://www.googleapis.com/drive/v3/files/FileID?key=APIKey
https://www.googleapis.com/drive/v3/files/FileID?alt=media&key=APIKey
https://drive.google.com/uc?id=FileID?alt=media&key=APIKey
https://drive.google.com/uc?id=FileID?key=APIKey

I am not sure if i am missing something.
My API seems to be working fine.
If i try https://www.googleapis.com/drive/v3/files/FileID?alt=media&key=APIKey it starts to download the file from the browser.
If i try https://www.googleapis.com/drive/v3/files/FileID?key=APIKey i can see the json also.

I have also added type="audio/mpeg" in the shortcode.

**Comment by birgire** [comment]
Hi @honoluluman2

The problem is related to the `&` in the track src attribute.

It's escaped so it becomes &#038;

Just to verify, what happens when you replace

        $data['src']                      = esc_url( $atts['src'] );

with

        $data['src']                      = esc_url_raw( $atts['src'] );

here

https://github.com/birgire/wpse-playlist/blob/a4aa1d1f40186047eb81d698d1cd4989110be2ca/php/class.playlist.php#L203

**Comment by honoluluman2** [comment]
Yes @birgire it was exactly this the problem!
With https://www.googleapis.com/drive/v3/files/FileID?alt=media&key=APIKey i am able to get the audio correct.
Should i keep the `esc_url_raw` there?

**Comment by honoluluman2** [comment]
How can i remove the  “  wrapped in the “Title” of the song?

**Comment by birgire** [comment]
@honoluluman2 yes keep it, I will put this later into the next plugin version.

The title quote is part of core translation string in `wp_underscore_playlist_templates()`:

https://github.com/WordPress/wordpress-develop/blob/0cb8475c0d07d23893b1d73d755eda5f12024585/src/wp-includes/media.php#L2637

and can be changed via normal WordPress translation.

**Comment by honoluluman2** [comment]
@birgire thank you very much for your help.
I know that my question may be out of the scope, but any help would be appreciated.
After one day of use with the google drive API links i am getting the following error

`{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
}` 

and of course i can not play the audio files. Similar to [this](https://stackoverflow.com/questions/69093990/daily-limit-for-unauthenticated-use-exceeded-continued-use-requires-signup-w). I am sure that there are not many users that could trigger the API download of the audio files.
 Any ideas would be appreciated.

**Comment by birgire** [comment]
@honoluluman2 

Try eg looking into api dashboard to check traffic and make sure the keys are valid. 

Also try to have the `key` GET parameter before `alt ` parameter in the links.

**Comment by birgire** [comment]
I've updated to version 0.0.11 with props to both of you @honoluluman2 and @mikigp

Thanks.
