### ISSUE TITLE
No longer works in WP 5.5

### ISSUE THREAD

**Issue by BlaineMoore** [birgire/wpse-playlist#21]
Great playlist plugin, been using it for years, but looks like WordPress made a change in 5.5 that has broken it. Any chance for an update to make it compatible with the latest changes?

**Comment by birgire** [comment]
Thanks @BlaineMoore, the demo seems to be still running on WP  5.5 here

https://xlino.com/projects/wordpress-playlist-shortcode-with-external-audio-or-video-files/

**Comment by BlaineMoore** [comment]
Interesting - must be some incompatibility w/something else I'm running then that for some reason is impacting your plugin? I downgraded back to 5.4.2 on a couple of sites and it started working again right away.

**Comment by birgire** [comment]
This comes to mind:

https://make.wordpress.org/core/2020/06/29/updating-jquery-version-shipped-with-wordpress/

**Comment by BlaineMoore** [comment]
Yup, that was the issue. Something I have installed is broken in regards to using your plugin, but installing the "Enable jQuery Migrate Helper" plugin got it working again after upgrading back to 5.5. Will have to track down the issue and we are in the process of upgrading to a new domain anyway which shouldn't have the issue. Thanks!
