### ISSUE TITLE
Jetpack 10.1

### ISSUE THREAD

**Issue by rmuthukrishnan** [birgire/wpse-playlist#22]
Hi @birgire ,  Thank you for the plugin. We have been using it successfully for a few years now.

But with the recent update of Jetpack from 10.0 to 10.1, it breaks.  We are also using wordpress 5.8.1.
The console shows the errors in the attachment.

I contacted Jetpack, and they said there were changes in Jetpack search that may have broken it. They are not ready to help as the plugin is not available through wordpress.org and is not mentioned as tested with latest wordpress.

When you find time, could you kindly take a look at the console error?
![Screenshot 2021-09-14 233703](https://user-images.githubusercontent.com/33143676/133726354-2ca09903-fcb5-4bee-916b-c66e30b2fc64.jpg)

Thank you for your help,
I am also parallelly investigating, 

Thank you,
Raman

**Comment by birgire** [comment]
Thank you @rmuthukrishnan for reporting
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
Does the native WP playlist work with Jetpack 10.1?

**Comment by rmuthukrishnan** [comment]
HI @birgire , thank you for your prompt response. I found that the issue happens with the WP native playlist as well. Also, I found that inserting the Slideshow block (I think, it is from Jetpack) is what breaks it. So, I will report the issue to Jetpack. Thank you again for your prompt help.

Raman

**Comment by birgire** [comment]
@rmuthukrishnan thanks for checking that out
