### ISSUE TITLE
How do I get the Next and Previous buttons to show?

### ISSUE THREAD

**Issue by cyberfunk** [birgire/wpse-playlist#6]
Hello,
I found examples of the native WordPress Audio player (MediaElement.js) with button controls for next and previous track but I can't figure out how to implement them. I'm using your excellent plugin and was wondering if I could add to the code to get the buttons to show. Any help is much appreciated. Here are examples of players with the controls enabled 

http://andrewberezovsky.ru/demo/backgroundaudio7/

http://sap.smartplugins.info/playlist/steamforged-fractured-singularity/

**Comment by birgire** [comment]
Hi @cyperfunk

The next/prev functionality works but there are no icons for them. The HTML is:

    <div class="wp-playlist-next"></div>
    <div class="wp-playlist-prev"></div>

I haven't played around with this, but I guess some CSS could make them visible. 

You might also check out [this question](http://wordpress.stackexchange.com/q/161127/26350)  and the two answers by bonger and taztodgmail on WordPress StackExchange.

**Comment by cyberfunk** [comment]
Thanks for your reply. I actually checked out the page you provided before I contacted you but the answers seem too complicated to easily implement. Can you provide the proper CSS code and where to put it to get the buttons to show up? I'm puzzled as to why the developers of MediaElement.js decided to leave the controls out.

**Comment by birgire** [comment]
As there has not been activity on this enhancement ticket for a long time, I close it for now, but welcome to open in the future.

**Comment by birgire** [comment]
As there has not been activity on this ticket for a long time, I close it for now, but welcome to open in the future.
