### ISSUE TITLE
Playlist writes 0/1 instead false/true into the wp-playlist-script

### ISSUE THREAD

**Issue by X-PRESSIVE** [birgire/wpse-playlist#7]
The plugin writes 0 or 1 into the wp-playlist-script instead of false or true as the original Wordpress playlist does. This causes compatibility issues when trying to read out the script using jQuery, for example.

Original Wordpress:

            <script class="wp-playlist-script" type="application/json">{
                "type":"audio",
                "tracklist":true,
                "tracknumbers":true,
                "images":true,
                "artists":false,
          </script>

Code generated by the plugin:

            <script class="wp-playlist-script" type="application/json">{
                "type":"audio",
                "tracklist":1,
                "tracknumbers":1,
                "images":1,
                "artists":0,
          </script>

**Comment by birgire** [comment]
Thanks for your comment, 

Version 0.0.8 should have this fixed.
