### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by nghipt99** [birgire/wpse-playlist#8]
Hi you!
i don't know include file and use your lib
i has uploaded All file to the folder wp-includes
Please help me!
my link web: https://procare24h.vn/10575-2/

**Comment by birgire** [comment]
Hi @nghipt99 

You can download the latest zip file from here:

    https://github.com/birgire/wpse-playlist/releases

and then upload that zip file through the:

    /wp-admin/plugin-install.php?tab=upload

and then activate it.

To use it, you have to add the playlist shortcode to the post/page content editor as explained in the readme file of the plugin, e.g. here

    https://github.com/birgire/wpse-playlist


Hope it helps.

**Comment by birgire** [comment]
I'm going to close this thread due to inactivity.

Hope it worked for you.
