### ISSUE TITLE
Thank You! Shortcode Question

### ISSUE THREAD

**Issue by BlaineMoore** [birgire/wpse-playlist#9]
Been about a year since I've visited this project but use it quite extensively. Most of my sites are on version 0.0.5 - just came in to grab the latest and greatest for a new project and it's nice to see all of the updates that have been made.

You note that the wpse_playlist shortcode is deprecated - is that going to be removed at some point or will it continue to work going forward? I'd hate to have to go in and update all of my existing sites and pages, though I'm happy enough to use the new shortcodes going forward.

Thank you also for the automatic updates, will be a while to get my previous sites updated (depending upon the answer to the above obviously) but it'll be nice to have fixes available on demand for projects going forward.

**Comment by birgire** [comment]
Hey @BlaineMoore 

Thanks for dropping by and commenting. Always good to hear from the users how they use the plugin and pros/cons about it.

I'm in no hurry to remove the old shortcodes and might even not remove it at all if you guys prefer to use it ;-) My main reason for changing the shortcode names was to make it easier for users to remember it  ;-)

Next on the roadmap is to support an order parameter (e.g. random).

All the best

**Comment by BlaineMoore** [comment]
Well, I don't prefer one over the other. I just don't relish the thought of going back and updating the hundreds of instances that I've already used it. Going forward I"ll use the new shortcodes, and worst case scenario I can write a SQL script to update them a site at a time at least en-masse. But...generally try to avoid direct SQL against my sites when possible, less chance of a typo causing problems.

Which reminds me, I do need to update my auto-text shortcut...heheh.

**Comment by birgire** [comment]
yes, I absolutely don't want to force uses making their hands dirty by writing some SQL scripts for this ;-)

If they would be deprecated in the future (at least not in the year 2016), I could create a short code snippet that would allow the use of the old shortcodes.

ps: I also want to wait and see the new shortcode API roadmap they are working on.
